//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCoordinates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointCoord
    {
        public int ID { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Icon { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
    }
}
